### ISSUE TITLE
Update pypi

### ISSUE THREAD

**Issue by jabdoa2** [arachnidlabs/cyflash#26]
Is there any chance you could update pypi to the latest version of this repository? https://pypi.python.org/pypi/cyflash/. That would be a huge help when using cyflash as a dependency in our project.

**Comment by jsiverskog** [comment]
@Arachnid can you help our here? AFAIK I don't have the permissions to do this.

**Comment by hardkrash** [comment]
A workaround is `pip install git+https://github.com/arachnidlabs/cyflash.git`
You can also set specific SHA checksums or tags too.
More details for the pip documentation. https://pip.pypa.io/en/latest/reference/pip_install/#git

**Comment by jabdoa2** [comment]
We will not ship git links in our pypi build. All dependencies should be loaded directly via pypi as well.

**Comment by C47D** [comment]
I have installed cyflash at work by using `pip install cyflash` and i'm getting the following error:

```
C:\Users\pc>cyflash -v
Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python36\Scripts\cyflash-script.py", line 11, in <module>
    load_entry_point('cyflash==1.6', 'console_scripts', 'cyflash')()
  File "c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2346, in load
    return self.resolve()
  File "c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\cyflash\bootload.py", line 218
    except (protocol.BootloaderError, BootloaderError), e:
                                                      ^
SyntaxError: invalid syntax
```

I'm guessing it's related to a no up to date version of cyflash on pypi?
